# Generated by Django 5.1.1 on 2024-09-21 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TodoApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listitem',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='listitem',
            name='is_completed',
        ),
    ]
